---
# tasks file for prometheus
- name: Add stable chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Create the namespace
  kubernetes.core.k8s:
    kind: Namespace
    name: monitoring
    state: present

- name: Delete the etcd-ca secret
  shell: |
    kubectl delete secret etcd-ca --ignore-not-found -n monitoring
  args:
    executable: /bin/bash

- name: Create the etcd-ca secret
  shell: |
    kubectl create secret generic etcd-ca --from-file=/etc/kubernetes/pki/etcd/server.crt --from-file=/etc/kubernetes/pki/etcd/server.key -n monitoring
  args:
    executable: /bin/bash

- name: Copy prometheus yaml
  template:
    src: "/home/acd/Desktop/ansible/roles/prometheus/templates/prometheus.yaml.j2"
    dest: "/home/acd/yaml/prometheus.yaml"
    mode: '0644'

- name: Install Jenkins Helm chart
  shell: |
    helm upgrade --install {{ prometheus_name }} oci://registry-1.docker.io/bitnamicharts/prometheus --namespace monitoring -f /home/acd/yaml/prometheus.yaml
  args:
    executable: /bin/bash
